# Generated by Django 3.2.7 on 2021-09-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('example_picture', models.ImageField(null=True, upload_to='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_focus', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('exercises', models.ManyToManyField(related_name='exercises', through='practiceplanapi.PlanExercise', to='practiceplanapi.Exercise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_of_session', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=150)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.player')),
                ('practice_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.practiceplan')),
            ],
        ),
        migrations.AddField(
            model_name='planexercise',
            name='practice_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.practiceplan'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.player'),
        ),
        migrations.AddField(
            model_name='category',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceplanapi.player'),
        ),
    ]
